name: app_dev_assign_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/bold_left_up_arrow.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
